default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: mano_ecommerce_api_development


test:
  <<: *default
  database: mano_ecommerce_api_test

production:
  primary: &primary_production
    <<: *default
    database: mano_ecommerce_api_production
    username: mano_ecommerce_api
    password: <%= ENV["MANO_ECOMMERCE_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: mano_ecommerce_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: mano_ecommerce_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: mano_ecommerce_api_production_cable
    migrations_paths: db/cable_migrate
